version: '3'
services:
  sqlserver:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - '5432:5432'
    volumes:
      - 'sqldata:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_PASSWORD=testme'

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    ports:
      - '8280:80'
    links:
      - sqlserver
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=login@email.com'
      - 'PGADMIN_DEFAULT_PASSWORD=testme'

volumes:
  sqldata:

